version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "slack_queue_bot"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql
  backend:
    # Name of the image
    image: backend-image
    # Backend directory
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      # <Port exposed> : < Backend Port running inside container>
      - 8080:8080
    volumes:
      # Where our data will be persisted
      - /data/spring-boot-app
    depends_on:
      # Initializes db first
      - db
    environment:
      # Adding docker specific config via profile
      - "SPRING_PROFILES_INCLUDE=docker"

# Names our volume
volumes:
  my-db: